### ISSUE TITLE
Proposal: Adapt metadata?

### ISSUE THREAD

**Issue by Kreyren** [spk121/potato-make#11]
In cargo-make i can define a rule/task as:

```toml
[tasks.kreyren]
description = "this task does some things"
category = "functional"
script = ...
```

that then allows me to list all the tasks as:

```console
kreyren@leonid ~/Repositories/RiXotStudio$ makers --list-all-steps
...
Tools
----------
build-file-increment - Increments (or creates) the build number in the build file, defined in CARGO_MAKE_BUILD_NUMBER_FILE environment variable.
build-file-increment-flow - Increments (or creates) the build number in the build file, defined in CARGO_MAKE_BUILD_NUMBER_FILE environment variable.
diff-files - Run diff on two provided files.
...

functional
----------
kreyren - this task does some things
...
```

Proposing this integration here as well to help with management of complicated projects which change rules depending on working directory.
